/*
Aman likes to play with strings, so his friend Riya decided to send him a mail, containing a sorted string with unique characters. But, due to some technical issue with her keyboard, whenever she presses a key, the corresponding character gets printed multiple times. Now Riya needs your help for removing all the unwanted characters from her string. For example, If aabbbccdef is a sorted string generated by Riya, then you should output the following string as answer abcdef.

Complete the function getDesiredString(str) that will take the string as parameter and modify it as specified.

Input Format:
The first line of input contains an integer T denoting the no of test cases . Then T test cases follow. Each test case contains a string str. 

Output Format:
For each test case, print the new string in new lines.

Constraints:
1 <= T <= 10
1 <= length of string <= 10^5
Each string will contain only lower-case English letters.﻿

Sample Input
2
aabbccdef
abddddddd

Sample Output
abcdef
abd
 */
import java.util.*;
public class TechnicalIssueWithKeyboard{
    private static String removeDuplicate(String str){
        StringBuilder sb = new StringBuilder();
        for(int i=0;i<str.length();i++){
            char currentChar = str.charAt(i);
            if(i+1<str.length() && str.charAt(i)==str.charAt(i+1)){
                continue;
            }
            sb.append(currentChar);
        }
        String newStr = sb.toString();
        return newStr;
    }
    public static void main(String[] args){
        Scanner S = new Scanner(System.in);
        System.out.print("Enter no of test cases: ");
        int test = S.nextInt();
        for(int i=0;i<test;i++){
            System.out.print("Enter a string: ");
            String str = S.next();
            System.out.println("Desired String:");
            System.out.println(removeDuplicate(str));
        }
        S.close();
    }
}